### ISSUE TITLE
rollup+bubleでモジュール連結した場合、デフォルト設定だとpageEffect発生時に固まる

### ISSUE THREAD

**Issue by segayuu** [getbasis/basis#11]
basis、未だCSSのノウハウが少ない自分にとっては本当にありがたい存在です。
特にgridが可変範囲で管理できるのが柔軟性が高くて助かります。
さて、rollup+bubleは本当にシンプルな生成を行ってくれます。
だからこそ、こういう問題がでたりしたのですが・・・

## 発生条件

以下の条件にてモジュール連結を行ったときに発生します。

```shell
$ npm i -D getbasis@4.3.0 jquery rollup rollup-plugin-node-resolve rollup-plugin-commonjs rollup-plugin-buble
```

```javascript
/* index.js */
const rollup = require('rollup').rollup;
const plugins = {
    npm: require('rollup-plugin-node-resolve'),
    cjs: require('rollup-plugin-commonjs'),
    buble: require('rollup-plugin-buble')
};

rollup({
    entry: './node_modules/getbasis/src/js/basis.js',
    plugins: [
        plugins.npm({
            browser: true
        }),
        plugins.cjs(),
        plugins.buble({
            //namedFunctionExpressions: false
            // ↑の設定がない場合に発生する
        })
    ]
}).then(bundle => bundle.write({ dest: 'bundle.js' }));
```

## 発生原因

上記条件にて生成されるbundle.jsは問題のある形で記述されます。

```javascript
/* bundle.js */
BasisPageEffect.prototype.location = function location (url) {
  setTimeout(function () {
    location.href = url; //↑の関数名に隠蔽されwindow.locationにアクセスできなくなる！
  }, this.params['duration']);
};
```

window.locationにアクセス出来ないので画面の更新がされず、そのまま固まります。

## 回避方法

v4.3.0時点にて上記問題を防ぐ方法で手っ取り早いのはindex.jsのコメントに記した通り
bubleのオプション設定である"namedFunctionExpressions: false"を設定することです。
この場合prototypeに代入されるのが無名関数になるのでwindow.locationが隠蔽されなくなり、アクセスが可能となります。

この挙動自体は素直なのですが、デフォルト設定だとこういう問題を引き起こしましたのでとりあえず報告させていただきたく思います。

**Comment by inc2734** [comment]
わー！ありがとうございます！ js よくわからずに書いているので本当にありがたいです（というか Basis を使っているという声もほとんど聞かないのでそれも嬉しいです！）。

js をよく理解しておらず、ご提示いただいた index.js の修正も実際にどこで行えば良いのかもよくわかりません。。Basis のデフォルトのビルドでいうと、gulpfile.js になるのでしょうか？もしよろしければプルリクいただけると大変助かります><

**Comment by segayuu** [comment]
早速の反応ありがとうございます。
ソースコードはともかく開発環境が職場にあるのでプルリクしようとすると月曜以降になってしまいますがご容赦ください。

babelですと関数名などが重複しないように構築しますが、
bubleですと素直さを重視した結果か、こういう競合が発生しました。
また、デフォルトでなければ回避の方法もある上にテストを月曜まで動かせないのでなんともですが、
一行で済む修正はこちら、ということで。
```javascript
/* page-effect.js */
location(url) { //←メソッド名をsetLocationなどに変える方とより鮮明？（注：こちらの変更は破壊的です）
  setTimeout(() => {
    //location.href = url
    window.location.href = url
    //↑一行だけでもwindowオブジェクトがローカル変数などで隠蔽されない限りアクセスできる
  }, this.params['duration']);
}
```

window.locationであることを明記しただけで上書き耐性がある程度できます。
ただ、個人的にはメソッド名を"setLocation"などに変更したほうがいいとおもいます。
（locationを設定するだけなのでsetのprefixあったほうがわかりやすい、かも、ということで）
とはいえ、メソッド名変更は曲がりなりにも破壊的変更なことになるのは注意してください。
